// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todos/v1/TodoService.proto

package todos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{0}
}
func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (dst *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(dst, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type ListTodoResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{1}
}
func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (dst *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(dst, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type CreateTodoRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{2}
}
func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(dst, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type RemoveTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTodoRequest) Reset()         { *m = RemoveTodoRequest{} }
func (m *RemoveTodoRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTodoRequest) ProtoMessage()    {}
func (*RemoveTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{3}
}
func (m *RemoveTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTodoRequest.Unmarshal(m, b)
}
func (m *RemoveTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTodoRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTodoRequest.Merge(dst, src)
}
func (m *RemoveTodoRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTodoRequest.Size(m)
}
func (m *RemoveTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTodoRequest proto.InternalMessageInfo

func (m *RemoveTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoRequest) Reset()         { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()    {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{4}
}
func (m *GetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoRequest.Unmarshal(m, b)
}
func (m *GetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoRequest.Merge(dst, src)
}
func (m *GetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodoRequest.Size(m)
}
func (m *GetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoRequest proto.InternalMessageInfo

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListTodosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodosRequest) Reset()         { *m = ListTodosRequest{} }
func (m *ListTodosRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodosRequest) ProtoMessage()    {}
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_TodoService_f341edea3b9bebd4, []int{5}
}
func (m *ListTodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodosRequest.Unmarshal(m, b)
}
func (m *ListTodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodosRequest.Marshal(b, m, deterministic)
}
func (dst *ListTodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodosRequest.Merge(dst, src)
}
func (m *ListTodosRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodosRequest.Size(m)
}
func (m *ListTodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodosRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TodoResponse)(nil), "todos.v1.TodoResponse")
	proto.RegisterType((*ListTodoResponse)(nil), "todos.v1.ListTodoResponse")
	proto.RegisterType((*CreateTodoRequest)(nil), "todos.v1.CreateTodoRequest")
	proto.RegisterType((*RemoveTodoRequest)(nil), "todos.v1.RemoveTodoRequest")
	proto.RegisterType((*GetTodoRequest)(nil), "todos.v1.GetTodoRequest")
	proto.RegisterType((*ListTodosRequest)(nil), "todos.v1.ListTodosRequest")
}

func init() {
	proto.RegisterFile("todos/v1/TodoService.proto", fileDescriptor_TodoService_f341edea3b9bebd4)
}

var fileDescriptor_TodoService_f341edea3b9bebd4 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0x95, 0x40, 0x29, 0xbd, 0xa2, 0x88, 0x1a, 0x84, 0x22, 0xb3, 0x44, 0x86, 0x01, 0x96,
	0x54, 0x0d, 0x0b, 0x12, 0x53, 0xe9, 0xc0, 0xc2, 0x14, 0x98, 0xd8, 0x80, 0xbc, 0xc1, 0x12, 0xe0,
	0x12, 0x9b, 0x7c, 0x13, 0xbe, 0x2f, 0xaa, 0x9d, 0xe0, 0xba, 0xff, 0xc6, 0xa7, 0xfb, 0xdd, 0xf3,
	0x9d, 0x6d, 0x70, 0xa3, 0x2a, 0xa5, 0xc7, 0xcd, 0x64, 0xfc, 0xac, 0x2a, 0xf5, 0x44, 0x75, 0x23,
	0xdf, 0x29, 0x9f, 0xd7, 0xca, 0x28, 0x76, 0x68, 0xb5, 0xbc, 0x99, 0xf0, 0x93, 0x80, 0x72, 0xb2,
	0x28, 0x70, 0xb4, 0x98, 0x4a, 0xd2, 0x73, 0xf5, 0xa5, 0x89, 0x09, 0xec, 0x2f, 0xb0, 0x34, 0xca,
	0xa2, 0xab, 0x61, 0x91, 0xe4, 0x9d, 0x3b, 0xb7, 0x94, 0xd5, 0xc4, 0x2d, 0x8e, 0x1f, 0xa5, 0x36,
	0x81, 0xef, 0x12, 0x3d, 0x8b, 0xa6, 0x51, 0xb6, 0xb7, 0xc1, 0xe8, 0x44, 0x71, 0x8d, 0xd1, 0xac,
	0xa6, 0x57, 0x43, 0xce, 0xfb, 0xfd, 0x43, 0xda, 0xb0, 0x53, 0xf4, 0x8c, 0x34, 0x1f, 0x64, 0xcf,
	0x1c, 0x94, 0x6e, 0x10, 0x17, 0x18, 0x95, 0xf4, 0xa9, 0x9a, 0x00, 0x4d, 0x10, 0xcb, 0xaa, 0xe5,
	0x62, 0x59, 0x89, 0x0c, 0xc9, 0x03, 0x99, 0x5d, 0x04, 0xf3, 0x59, 0x75, 0xcb, 0x14, 0xbf, 0x31,
	0x86, 0x4b, 0x17, 0xc5, 0xa6, 0x80, 0x4f, 0xc5, 0xce, 0x7d, 0xf4, 0xb5, 0xac, 0xfc, 0x6c, 0xa5,
	0x57, 0x57, 0x7f, 0x0a, 0xf8, 0xb4, 0xcb, 0x2b, 0xd6, 0x3a, 0x6c, 0x5d, 0x71, 0x87, 0x7e, 0xdb,
	0x85, 0xa5, 0x1e, 0x09, 0xeb, 0x6d, 0x35, 0xcf, 0x30, 0xf8, 0xaf, 0xc9, 0xb8, 0x87, 0x56, 0xbb,
	0xf3, 0x0d, 0x5a, 0xb7, 0xe4, 0xbe, 0xff, 0xe2, 0x9e, 0xe9, 0xed, 0xc0, 0xfe, 0x8d, 0x9b, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x7a, 0x77, 0xa0, 0x58, 0x02, 0x00, 0x00,
}
