// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todos/v1/Todo.proto

package todos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoState int32

const (
	TodoState_UNKNOWN  TodoState = 0
	TodoState_ARCHIVED TodoState = 1
	TodoState_ACTIVE   TodoState = 2
)

var TodoState_name = map[int32]string{
	0: "UNKNOWN",
	1: "ARCHIVED",
	2: "ACTIVE",
}
var TodoState_value = map[string]int32{
	"UNKNOWN":  0,
	"ARCHIVED": 1,
	"ACTIVE":   2,
}

func (x TodoState) String() string {
	return proto.EnumName(TodoState_name, int32(x))
}
func (TodoState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Todo_e59cc9ffca006d5a, []int{0}
}

type Todo struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	State                TodoState `protobuf:"varint,3,opt,name=state,proto3,enum=todos.v1.TodoState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Todo_e59cc9ffca006d5a, []int{0}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetState() TodoState {
	if m != nil {
		return m.State
	}
	return TodoState_UNKNOWN
}

func init() {
	proto.RegisterType((*Todo)(nil), "todos.v1.Todo")
	proto.RegisterEnum("todos.v1.TodoState", TodoState_name, TodoState_value)
}

func init() { proto.RegisterFile("todos/v1/Todo.proto", fileDescriptor_Todo_e59cc9ffca006d5a) }

var fileDescriptor_Todo_e59cc9ffca006d5a = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xc9, 0x4f, 0xc9,
	0x2f, 0xd6, 0x2f, 0x33, 0xd4, 0x0f, 0xc9, 0x4f, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x0b, 0xea, 0x95, 0x19, 0x2a, 0x85, 0x73, 0xb1, 0x80, 0xc4, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58,
	0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0x42, 0x10, 0x8e, 0x90, 0x26, 0x17, 0x6b, 0x71,
	0x49, 0x62, 0x49, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0xb0, 0x1e, 0xcc, 0x1c, 0x3d,
	0x90, 0x21, 0xc1, 0x20, 0xa9, 0x20, 0x88, 0x0a, 0x2d, 0x23, 0x2e, 0x4e, 0xb8, 0x98, 0x10, 0x37,
	0x17, 0x7b, 0xa8, 0x9f, 0xb7, 0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0x83, 0x10, 0x0f, 0x17, 0x87, 0x63,
	0x90, 0xb3, 0x87, 0x67, 0x98, 0xab, 0x8b, 0x00, 0xa3, 0x10, 0x17, 0x17, 0x9b, 0xa3, 0x73, 0x88,
	0x67, 0x98, 0xab, 0x00, 0x93, 0x13, 0x7b, 0x14, 0x2b, 0xd8, 0xc0, 0x24, 0x36, 0xb0, 0x33, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45, 0xad, 0x6c, 0x43, 0xbd, 0x00, 0x00, 0x00,
}
