// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todos/v1/types.proto

package todos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoState int32

const (
	TodoState_UNKNOWN  TodoState = 0
	TodoState_ARCHIVED TodoState = 1
	TodoState_ACTIVE   TodoState = 2
)

var TodoState_name = map[int32]string{
	0: "UNKNOWN",
	1: "ARCHIVED",
	2: "ACTIVE",
}

var TodoState_value = map[string]int32{
	"UNKNOWN":  0,
	"ARCHIVED": 1,
	"ACTIVE":   2,
}

func (x TodoState) String() string {
	return proto.EnumName(TodoState_name, int32(x))
}

func (TodoState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_475d3f1157d5af90, []int{0}
}

type Todo struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	State                TodoState `protobuf:"varint,3,opt,name=state,proto3,enum=todos.v1.TodoState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_475d3f1157d5af90, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetState() TodoState {
	if m != nil {
		return m.State
	}
	return TodoState_UNKNOWN
}

func init() {
	proto.RegisterEnum("todos.v1.TodoState", TodoState_name, TodoState_value)
	proto.RegisterType((*Todo)(nil), "todos.v1.Todo")
}

func init() { proto.RegisterFile("todos/v1/types.proto", fileDescriptor_475d3f1157d5af90) }

var fileDescriptor_475d3f1157d5af90 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xc9, 0x4f, 0xc9,
	0x2f, 0xd6, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0x8b, 0xea, 0x95, 0x19, 0x2a, 0x85, 0x73, 0xb1, 0x84, 0xe4, 0xa7, 0xe4, 0x0b,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08,
	0x89, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0x30, 0x81, 0x85, 0x20, 0x1c, 0x21, 0x4d,
	0x2e, 0xd6, 0xe2, 0x92, 0xc4, 0x92, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x61, 0x3d,
	0x98, 0x39, 0x7a, 0x20, 0x43, 0x82, 0x41, 0x52, 0x41, 0x10, 0x15, 0x5a, 0x46, 0x5c, 0x9c, 0x70,
	0x31, 0x21, 0x6e, 0x2e, 0xf6, 0x50, 0x3f, 0x6f, 0x3f, 0xff, 0x70, 0x3f, 0x01, 0x06, 0x21, 0x1e,
	0x2e, 0x0e, 0xc7, 0x20, 0x67, 0x0f, 0xcf, 0x30, 0x57, 0x17, 0x01, 0x46, 0x21, 0x2e, 0x2e, 0x36,
	0x47, 0xe7, 0x10, 0xcf, 0x30, 0x57, 0x01, 0x26, 0x27, 0xf6, 0x28, 0x56, 0xb0, 0x81, 0x49, 0x6c,
	0x60, 0x67, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xe1, 0x42, 0xb2, 0xbe, 0x00, 0x00,
	0x00,
}
