// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo/service.proto

package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TestEnum has a comment
type Test int32

const (
	Test_UNKNOWN Test = 0
	// So does this value
	Test_HELLO Test = 1
	Test_THERE Test = 2
)

var Test_name = map[int32]string{
	0: "UNKNOWN",
	1: "HELLO",
	2: "THERE",
}
var Test_value = map[string]int32{
	"UNKNOWN": 0,
	"HELLO":   1,
	"THERE":   2,
}

func (x Test) String() string {
	return proto.EnumName(Test_name, int32(x))
}
func (Test) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_d66656aa490b70e8, []int{0}
}

// EchoRequest only passes a message
type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_d66656aa490b70e8, []int{0}
}
func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (dst *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(dst, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// EchoResponse only contains a message
type EchoResponse struct {
	// message that was in the request
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_d66656aa490b70e8, []int{1}
}
func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (dst *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(dst, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "demo.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "demo.EchoResponse")
	proto.RegisterEnum("demo.Test", Test_name, Test_value)
}

func init() { proto.RegisterFile("demo/service.proto", fileDescriptor_service_d66656aa490b70e8) }

var fileDescriptor_service_d66656aa490b70e8 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x29, 0xa9, 0x73, 0x71, 0xbb, 0x26, 0x67, 0xe4, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4a, 0x1a, 0x5c, 0x3c, 0x10, 0x85, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0xb8, 0x55, 0x6a, 0x69, 0x72, 0xb1, 0x84, 0x80, 0xcc, 0xe2, 0xe6, 0x62, 0x0f, 0xf5, 0xf3,
	0xf6, 0xf3, 0x0f, 0xf7, 0x13, 0x60, 0x10, 0xe2, 0xe4, 0x62, 0xf5, 0x70, 0xf5, 0xf1, 0xf1, 0x17,
	0x60, 0x04, 0x31, 0x43, 0x3c, 0x5c, 0x83, 0x5c, 0x05, 0x98, 0x8c, 0x6c, 0xb8, 0xb8, 0x5d, 0x52,
	0x73, 0xf3, 0x83, 0x21, 0x0e, 0x13, 0xd2, 0xe5, 0x62, 0x01, 0xd9, 0x21, 0x24, 0xa8, 0x07, 0x72,
	0x9b, 0x1e, 0x92, 0xc3, 0xa4, 0x84, 0x90, 0x85, 0x20, 0x4e, 0x70, 0x62, 0x8b, 0x02, 0xfb, 0x21,
	0x89, 0x0d, 0xec, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x9e, 0x33, 0x88, 0xe6,
	0x00, 0x00, 0x00,
}
