// generated by protoc-gen-tweact. DO NOT EDIT.
// source: todos/v1/service.proto

import { TwirpService } from "@department/twirp-component";

export interface Todo {
  id: string;

  title: string;

  state: TodoState;
}
export interface TodoResponse {
  todo: Todo;
}
export interface ListTodoResponse {
  todos: Todo[];
}
export interface CreateTodoRequest {
  title: string;
}
export interface RemoveTodoRequest {
  id: string;
}
export interface GetTodoRequest {
  id: string;
}
export interface ListTodosRequest {}
export enum TodoState {
  UNKNOWN = 0,

  ARCHIVED = 1,

  ACTIVE = 2
}

export class CreateTodo extends TwirpService<CreateTodoRequest, TodoResponse> {
  method = "todos.v1.TodoService/CreateTodo";
}
export class RemoveTodo extends TwirpService<RemoveTodoRequest, TodoResponse> {
  method = "todos.v1.TodoService/RemoveTodo";
}
export class GetTodo extends TwirpService<GetTodoRequest, TodoResponse> {
  method = "todos.v1.TodoService/GetTodo";
}
export class ListTodos extends TwirpService<
  ListTodosRequest,
  ListTodoResponse
> {
  method = "todos.v1.TodoService/ListTodos";
}
