// generated by protoc-gen-tweact. DO NOT EDIT.
// source: todos/v1/Todo.proto

interface TwirpClient<Req, Res> {
  request(method: string, variables: Partial<Req>, options: any): Promise<Res>;
}

export interface Todo {
  id?: string;
  title?: string;
  state?: TodoState;
}
export enum TodoState {
  UNKNOWN = 0,
  ARCHIVED = 1,
  ACTIVE = 2,
}