package generator

import "text/template"

type dependency struct {
	Name string
	Path string
}

type header struct {
	Imports []dependency
	Source  string
	Comment string
}

var headerTemplate = template.Must(template.New("header").Parse(`// generated by protoc-gen-tweact. DO NOT EDIT.
// source: {{.Source}}

{{- .Comment}}

{{- range .Imports }}
import {{ .Name }} from "{{ .Path }}"
{{- end}}

interface TwirpClient<Req, Res> {
  request(method: string, variables: Partial<Req>, options: any): Promise<Res>;
}
`))
