// generated by protoc-gen-tweact. DO NOT EDIT.
// source: demo/service.proto
/**
 * File comments can be useful too
 */
/**
 * DemoService shows a very simple service with only
 * an Echo method.
 */

import { withTwirp, TwirpService } from "@department/twirp-component";

/**
 * EchoRequest only passes a message
 */
export interface EchoRequest {
	
/**
 * message to echo
 */
  message: string;
}
/**
 * EchoResponse only contains a message
 */
export interface EchoResponse {
	
/**
 * message that was in the request
 */
  message: string;
}
/**
 * TestEnum has a comment
 */
export enum Test {
  
  UNKNOWN = 0,
  
/**
 * So does this value
 */
  HELLO = 1,
  
/**
 * and trailing
 */
  THERE = 2,
}

/**
 * Echo responds with the message passed into the
 * request. Useful for testing and as a minimal
 * example.
 */
export const Echo = withTwirp(
  class Echo extends TwirpService<EchoRequest, EchoResponse> {
    constructor(props: any) {
      super("demo.DemoService/Echo", props);
    }
  }
);