// generated by protoc-gen-tweact
import { withTwirp, TwirpService } from "@department/twirp-component";

export interface EchoRequest {
  message: string;
}
export interface EchoResponse {
  message: string;
}

export const Echo = withTwirp(
  class Echo extends TwirpService<EchoRequest, EchoResponse> {
    constructor(props: any) {
      super("demo.DemoService/Echo", props);
    }
  }
);
